[package]
name = "ftp_em"
version = "0.1.0"
authors = ["Huy Hoang Phan <hoangph271@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
